version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${MSSQL_PASSWORD}"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - db
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "/opt/mssql-tools/bin/sqlcmd -S db -U ${MSSQL_USER} -P '${MSSQL_PASSWORD}'
      -Q \"IF DB_ID('${MSSQL_DB}') IS NULL CREATE DATABASE ${MSSQL_DB};\""
    restart: "no"

  api:
    build: .
    container_name: apiarquitetura
    depends_on:
      - db
      - db-init
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${APP_PORT}:8080"
    restart: always

volumes:
  mssql_data: