# === DataSource (serviço db do docker-compose) ===
spring.datasource.url=jdbc:sqlserver://db:1433;databaseName=ApiArquiteturaDB;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# === Inicializa dos scripts ===
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data-test.sql

# === Login simples (in-memory) para ambiente docker ===
spring.security.user.name=admin
spring.security.user.password=admin@123
spring.security.user.roles=ADMIN

# === Desativa OAuth2 neste ambiente ===
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration
